#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $BLACKPANTHER_REPO == "blackpantherbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL09QQkxBQ0tQQU5USEVSUy9CTEFDSy1QQU5USEVSUy1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $BLACKPANTHER_REPO == "BLACKPANTHERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL09QQkxBQ0tQQU5USEVSUy9CTEFDSy1QQU5USEVSUy1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $BLACKPANTHER_REPO =~ $regex ]]
    then
        if [[ $BLACKPANTHER_REPO_BRANCH ]]
        then
            echo "${BLACKPANTHER_REPO}/archive/${BLACKPANTHER_REPO_BRANCH}.zip"
        else
            echo "${BLACKPANTHER_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL09QQkxBQ0tQQU5USEVSUy9CTEFDSy1QQU5USEVSUy1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="blackpantherbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    BLACKPANTHERPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $BLACKPANTHERPATH
    echo "    Starting BlackPantherBot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          ║║║║║╠╣║╔╝╔║║╣╠╣║╔╗║║║║║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
